### ISSUE TITLE
Redis single point of failure

### ISSUE THREAD

**Issue by lhtrieu87** [agouaillard/Large-Long-Lived-Connections-Challenge#5]
As mentioned in your presentation, Redis store is used as event bus to broadcast events between web socket servers. What is your plan to scale this? This is just for discussion (no need to implement).

**Comment by agouaillard** [comment]
Well, in this challenge there is no mention of interaction between clients. You mentioned that you want clients to send messages to the server and that s it.

In most cases though you will want clients to speak to each other, and to achieve good scalability you will use more than one server. In that case, a reais store (in pub/sub mode) is really the best way to go. Note that you usually do not give users the capacity to publish platform-wide. There is usually a lower level of granularity (room, realm, ....) that allows to limit the impact of a single message from a single user. Most people start by (brutally) mapping 1 virtual room to 1 instance, before going multi-tenant, and doing other kind of optimisation. For chat apps, the CPU is the bottle neck, so you want to optimise quickly, but for Gaming and/or Media apps (audio/video conferencing), bandwidth is always the bottle neck, and also represents 80% of the cost, so you do not really care if you waste CPU cycles in the cloud.

In terms of single point of failure, your front-load balancer is a bigger risk than your Redis DB. First it is really a single point. That can be mitigated by using DNS dispatching approaches and other queues. At citrix, we would use AWS's [route 53](https://aws.amazon.com/route53/) to handle advance DNS functions, and achieve roughly 1 millions minutes of audio call a month across all the GoTo products (GoToMeeting, GoToWebinar, GoToTraining, ...).

Then, the Redis implementation is usually provided in a very efficient way by your cloud provider. I'm most familiar with AWS ElasticCache ([here](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/WhatIs.html)), but I'm pretty sure that every cloud vendor provides the equivalent.

Setting up each function as a micro service reduce the maintenance, reduce the opportunity for failure and allow for better scalability over all.

I hope this answers your question, in which case please go ahead and close this issue. Otherwise, feel free to ask more questions, or we can have a Skype chat.

**Comment by lhtrieu87** [comment]
Thanks for your quick answer and shared information. You are right Load Balancer is a bigger concern for single point of failure. 

At Holmusk, we implemented the chat feature with the architect which is similar to the one in your presentation, using Redis as pub/sub to route the messages to interested receivers. The pain point here is that we need to handle HIPPA [http://www.hhs.gov/hipaa/](url). AWS elastic cache and other Redis/similar services providers do not sign HIPPA agreement. Therefore, we may have to handle pub/sub cluster ourselves in EC2 instances.

**Comment by agouaillard** [comment]
Ha! American regulations can be a pain! I had to deal with that all the time when working on ITK (since the software ultimately was bundled with medical devices, used in hospitals, I had to deal with FDA white book). I resent their antiquated rule with a passion ...

There are many ways around though, but you're right, it requires extra work, since you have to handle all the extra service amazon would otherwise provide yourself, and fall back to managed cluster of instances. Yuck. Ben there, Done that, Hated it.
